// 1729 — English UI strings (primary language)

const en = {
  giftWord: 'gift',

  auth: {
    signup: 'Sign up',
    login: 'Log in',
    email: 'Email',
    password: 'Password',
    processing: 'Processing',
    error: 'Something went wrong. Want to try again?',
  },

  onboarding: {
    screen1: { headline: 'No name here. No title. No history. Just you.', cta: 'Ready' },
    screenVillage: {
      line1: 'Welcome.',
      line2: 'You arrived here with an invitation. Maybe the person who invited you couldn\'t quite explain what it is — that\'s okay, because 1729 is something lived, not described.',
      line3: 'Think of it this way: a small village. Everyone carries a burden, everyone holds a gift. But most of us live in the wrong village — where nobody knows anyone, everyone tries to do everything alone, and exhausts themselves. While you\'re struggling with something, someone two doors down might do it with ease. The work that drains you might be someone else\'s favorite thing.',
      line4: '1729 is an attempt to build that village, small and from scratch. This is not a marketplace, not a noisy space — it\'s a small, closed, trusted circle. You enter by invitation, because trust doesn\'t grow in crowds; it grows in familiar faces.',
      line5: 'We\'ll ask you four questions to get started. We\'re not looking for right answers; we\'re looking for you. Take your time — these aren\'t questions to rush through. At the end, we\'ll prepare a gift card from your answers: a small card showing what you can offer the community. You can edit it however you like.',
      cta: 'Ready, let\'s begin.',
    },
    screen2: {
      atmospheric: 'When you were a child, there was something you did for hours — no praise needed, no assignment required. Maybe you were drawing, taking things apart and putting them back, or just listening to someone. Then we grew up and everything had to \'be useful.\' Set aside that filter for a moment.',
      question: "If you had nothing to prove and nothing you were supposed to do — what would you spend your time on? What's the thing you lose track of time doing?",
      cta: 'Continue',
    },
    screen3: {
      atmospheric: 'There are moments when a whole roomful of people have been stuck on something for hours, and you shrug and solve it. Maybe you\'ve said \'come on, it\'s really not that hard.\' But for them, it truly was hard — it just wasn\'t for you. Right there, in what you think of as totally normal, something rare is hiding.',
      question: 'What do you feel like you\'re getting away with? The things that are genuinely hard for others but feel almost like play to you — what are those?',
      cta: 'Continue',
    },
    screen4: {
      atmospheric: 'And there\'s another kind: work you can do, but that takes something out of you every time. When you finish, you don\'t feel relief — just tired. For years we call this a \'lack of discipline,\' but often it simply means: this isn\'t your work, it\'s someone else\'s. And that someone else might be your neighbor in this village, just two doors down.',
      question: "What kind of work drains you? You can do it, but something gets pulled out of you every time. What are the areas where you'd welcome a neighbor's touch?",
      cta: 'Continue',
    },
    screen6: {
      explanation: 'Now here\'s my favorite question. Imagine: a small village, everyone putting something forward. One day your neighbor knocks on your door — and before they\'ve even explained their problem, something quietly lights up in you. Because you\'ve been waiting for someone to ask exactly this. You end up being the one who gives, and the one who is filled. I spent years looking for this in the wrong places; it turned out it was always the thing that came most easily, most naturally.\n\nThis is the card you leave for the community. We\'re preparing a draft below — edit it however you like.',
      question: 'What is that thing? What would you give to your community that would genuinely fill you up too?',
      optionalLabel: 'Optional',
      optionalPlaceholder: 'Why you, and not someone else?',
      cta: 'Create my gift',
    },
    screen7: { ready: 'Your gift is ready.', cta: 'Continue' },
    saving: 'Saving',
    textareaPlaceholder: 'Write here.',
  },

  nav: {
    dashboard: 'Home',
    questions: 'Questions',
    trustTeam: 'Trust Circle',
    explore: 'Explore',
    give: 'Give',
    settings: 'Settings',
    signOut: 'Sign out',
  },

  dashboard: {
    activeCards: 'Active gifts',
    supportGiven: 'Gifts given',
    supportReceived: 'Gifts received',
    trustTeamSize: 'Trust circle',
    recentActivity: 'Recent activity',
    noActivity: 'Nothing here yet.',
    gave: 'You gave a gift.',
    received: 'You received a gift.',
    quickActions: {
      createCard: 'New gift',
      createCardDesc: 'Create a new gift card.',
      explore: 'Explore',
      exploreDesc: 'Browse gifts from your circle and beyond.',
      editQuestions: 'Edit questions',
      editQuestionsDesc: 'Update your answers.',
      trustTeam: 'Trust Circle',
      trustTeamDesc: 'Manage your circle and invitations.',
    },
  },

  give: {
    title: 'Give',
    subtitle: 'Manage your gift cards.',
    tabMy: 'My gifts',
    tabHistory: 'Given',
    cardActive: 'Active',
    cardInactive: 'Paused',
    newCard: 'New gift',
    newCardTitle: 'New gift',
    titleLabel: 'Title',
    descLabel: 'Description',
    // Gift type
    giftTypeLabel: 'Type',
    typeUnlimited: 'Always open',
    typeUnlimitedHint: 'No limit — always available.',
    typeQuota: 'Limited',
    typeQuotaHint: 'A set number of uses.',
    typeOnce: 'One-time',
    typeOnceHint: 'One person takes it, then it closes.',
    quotaLabel: 'How many?',
    // Physical
    physicalLabel: 'Format',
    digital: 'Digital',
    physical: 'Physical',
    deliveryNoteLabel: 'Delivery note',
    deliveryNotePlaceholder: 'Anything about shipping or handoff? (optional)',
    deliveryNoteHint: 'Logistics are handled between you two — the platform doesn\'t coordinate.',
    // Visibility
    visibilityLabel: 'Visibility',
    visTrustCircle: 'Trust Circle',
    visCommunity: 'Community',
    visGlobal: 'Global',
    comingSoon: 'Coming soon',
    // Other
    whyMeLabel: 'Why you?',
    whyMePlaceholder: 'Why you, and not someone else?',
    optional: 'optional',
    create: 'Create',
    cancel: 'Cancel',
    creating: 'Creating',
    empty: 'No gifts yet.',
    historyEmpty: 'You haven\'t given any gifts yet.',
    error: 'Something went wrong. Want to try again?',
    // Card badges
    badgeUnlimited: 'Always open',
    badgeOnce: 'One-time',
    badgeQuota: (n) => `${n} left`,
    badgePhysical: 'Physical',
    interested: (n) => n === 1 ? '1 request' : `${n} requests`,
  },

  explore: {
    title: 'Explore',
    subtitle: 'Browse gifts from your circle and beyond.',
    tabFeed: 'Gifts',
    tabHistory: 'Received',
    filterTrustCircle: 'Trust Circle',
    filterCommunity: 'Community',
    filterGlobal: 'Global',
    filterAll: 'All',
    filterUnlimited: 'Always open',
    filterQuota: 'Limited',
    filterOnce: 'One-time',
    filterPhysical: 'Physical',
    requestSupport: 'Request',
    requesting: 'Sending',
    empty: 'Nothing here yet.',
    historyEmpty: 'You haven\'t received any gifts yet.',
    error: 'Something went wrong. Want to try again?',
    markReceived: 'Mark as received',
    addToCircle: 'Add to your circle?',
    addToCircleHint: 'You received a gift from this person. Would you like to add them to your trust circle?',
    addToCircleYes: 'Add',
    addToCircleSkip: 'Skip',
    added: 'Added.',
    comingSoon: 'Coming soon',
  },

  questions: {
    title: 'Questions',
    subtitle: 'View and edit your answers.',
    save: 'Save',
    saving: 'Saving',
    saved: 'Saved.',
    createCardLabel: 'Create a gift card from this answer.',
    error: 'Something went wrong. Want to try again?',
  },

  trustTeam: {
    title: 'Trust Circle',
    subtitle: 'Your trust circle and the people you\'ve invited.',
    tabCircle: 'Trust Circle',
    tabInvited: 'Invited',
    invite: 'Invite',
    emptyCircle: 'Your trust circle is empty.',
    emptyCircleHint: 'After receiving a gift, mark it as received to add that person here.',
    emptyInvited: 'You haven\'t invited anyone yet.',
    subscriptionActive: 'Active',
    subscriptionEnded: 'Ended',
    subscriptionPending: 'Pending',
    daysLeft: (n) => `${n}d left`,
    endSubscription: 'End',
    gaveGift: 'gave you a gift',
    modal: {
      title: 'Invite someone',
      step1: 'Their email',
      step2: 'Duration',
      step3: 'Community',
      step4: 'Code',
      emailLabel: 'Email address',
      emailPlaceholder: 'name@example.com',
      duration1: '1 month',
      duration6: '6 months',
      duration12: '12 months',
      communityNew: 'New community',
      communityGeneral: 'General (no community)',
      communityExisting: 'Existing community',
      communityNameLabel: 'Community name',
      membersAwareLabel: 'Members will know they\'re in a named group',
      next: 'Next',
      back: 'Back',
      generate: 'Generate code',
      codeReady: 'Share this code',
      codeHint: 'They\'ll need this to join.',
      copy: 'Copy',
      copied: 'Copied!',
      close: 'Done',
    },
  },

  payment: {
    title: 'Join 1729',
    subtitle: 'You need an invite code to continue.',
    codeLabel: 'Invite code',
    codePlaceholder: 'XXXXXX',
    apply: 'Apply',
    invalidCode: 'Invalid or already used code.',
    codeAccepted: 'Code accepted.',
    requireCode: 'An invite code is required.',
    continue: 'Continue',
    processing: 'Processing',
    testMode: 'Test mode — no real payment.',
    error: 'Something went wrong. Want to try again?',
  },

  settings: {
    title: 'Settings',
    subtitle: 'Manage your account and preferences.',

    // Appearance
    appearance: 'Appearance & Language',
    theme: 'Theme',
    themeDark: 'Dark',
    themeLight: 'Light',
    themeSystem: 'System',
    language: 'Language',
    giftWord: 'Gift word',
    giftWordDefault: 'Gift',
    giftWordAlt: 'Thing',
    giftWordNote: 'This is only visible to you — others always see their own preference.',

    // Subscription
    subscription: 'Subscription',
    plan: 'Plan',
    startDate: 'Start date',
    endDate: 'End date',
    daysLeft: (n) => `${n} day${n === 1 ? '' : 's'} left`,
    type: 'Type',
    typeGifted: 'Gifted by someone',
    typeSelf: 'Self-subscribed',
    managePayment: 'Manage payment',
    comingSoon: 'Coming soon',

    // Notifications
    notifications: 'Email notifications',
    notifGiftInterest: 'Someone is interested in your gift',
    notifGiftInterestHint: 'When a conversation starts around your gift.',
    notifNewMessage: 'New message',
    notifNewMessageHint: 'When you receive a new message in an active conversation.',
    notifSubExpiring: 'Subscription expiring soon',
    notifSubExpiringHint: '5 days before your access ends.',
    notifSubExpired: 'Subscription ended',
    notifSubExpiredHint: 'When your access expires.',
    notifAddedToCircle: 'Added to someone\'s circle',
    notifAddedToCircleHint: 'When someone adds you to their trust circle.',
    notifQuotaEmpty: 'Gift quota reached',
    notifQuotaEmptyHint: 'When a limited gift runs out of uses.',

    // Account
    account: 'Account',
    emailLabel: 'Email address',
    changePassword: 'Change password',
    newPassword: 'New password',
    updatePassword: 'Update',
    passwordUpdated: 'Password updated.',
    dangerZone: 'Danger zone',
    deleteAccount: 'Permanently delete your account and all data.',
    deleteConfirmPlaceholder: 'Type DELETE to confirm',
    deleteConfirmWord: 'DELETE',
    confirmDelete: 'Permanently delete',

    saved: 'Saved.',
    error: 'Something went wrong. Try again?',
  },

  language: { label: 'Language', en: 'English', tr: 'Türkçe' },

  errors: {
    generic: 'Something went wrong. Want to try again?',
    dbError: 'Connection failed.',
  },
}

export default en
