// 1729 — Turkish UI strings (secondary language)

const tr = {
  giftWord: 'armağan',

  auth: {
    signup: 'Kayıt Ol',
    login: 'Giriş Yap',
    email: 'E-posta',
    password: 'Şifre',
    processing: 'İşleniyor',
    error: 'Bir şey olmadı. Tekrar dener misin?',
  },

  onboarding: {
    screen1: { headline: 'Burada adın yok. Unvanın yok. Geçmişin yok. Sadece sen varsın.', cta: 'Hazırım' },
    screenVillage: {
      line1: 'Bir köy hayal et.',
      line2: 'Kimsenin unvanı yok.',
      line3: 'Kimse bir şey kanıtlamak zorunda değil.',
      line4: 'Herkes bir şeyler getirir. Herkes bir şeyler alır.',
      cta: 'Devam',
    },
    screen2: { atmospheric: 'Burada kimse seni izlemiyor.', question: "Kanıtlayacak hiçbir şeyin, yapman 'gereken' hiçbir şey olmasaydı — vaktini nelerle geçirmekten en çok keyif alırdın? Neyle uğraşırken zamanın nasıl geçtiğini fark etmezdin?", cta: 'Devam' },
    screen3: { atmospheric: 'Bu bir yetenek testi değil.', question: 'Hangi konularda hile yapıyormuş gibi hissediyorsun? Başkaları için gerçekten zor olan ama senin için biraz oyun gibi olan şeyler — onlar neler?', cta: 'Devam' },
    screen4: { atmospheric: 'Almak da bir cesaret işidir.', question: 'Hangi işler enerjini tüketiyor? Yapabilirsin ama içinden gelmiyor, her seferinde bir şeyler emiyor. Bir komşunun dokunuşuna ihtiyaç duyduğun alanlar neler?', cta: 'Devam' },
    screen5: { text: 'Son soru biraz farklı.\nCevabın bir kart olacak.\nBiri görebilecek. Talep edebilecek.\nSen de istersen vereceksin — istersen vermeyeceksin.\nAma şimdi sadece dürüstçe yaz.', cta: 'Devam' },
    screen6: { question: 'O hayalindeki köyde komşun kapını çalıp destek istiyor; ve sen uçarak gidiyorsun. Çünkü zaten birinin bunu senden istemesini bekliyormuşsun. O şey ne? Topluluğuna vermekten gerçekten memnun olacağın, seni de dolduracak olan şey nedir?', optionalLabel: 'İsteğe bağlı', optionalPlaceholder: 'Bunu neden sen veriyorsun, başkası değil?', cta: 'Armağanımı Oluştur' },
    screen7: { ready: 'Armağanın hazır.', cta: 'Devam Et' },
    saving: 'Kaydediliyor',
    textareaPlaceholder: 'Buraya yaz.',
  },

  nav: {
    dashboard: 'Panel',
    questions: 'Sorular',
    trustTeam: 'Güven Çemberi',
    explore: 'Keşfet',
    give: 'Ver',
    settings: 'Ayarlar',
    signOut: 'Çıkış',
  },

  dashboard: {
    activeCards: 'Aktif Armağan',
    supportGiven: 'Verilen Armağan',
    supportReceived: 'Alınan Armağan',
    trustTeamSize: 'Güven Çemberi',
    recentActivity: 'Son Hareketler',
    noActivity: 'Henüz kimse burada değil.',
    gave: 'Bir armağan verdin.',
    received: 'Bir armağan aldın.',
    quickActions: {
      createCard: 'Yeni Armağan',
      createCardDesc: 'Yeni bir armağan kartı oluştur.',
      explore: 'Keşfet',
      exploreDesc: 'Güven çemberinden ve ötesinden armağanlara göz at.',
      editQuestions: 'Soruları Düzenle',
      editQuestionsDesc: 'Cevaplarını güncelle.',
      trustTeam: 'Güven Çemberi',
      trustTeamDesc: 'Güven çemberini ve davetlerini yönet.',
    },
  },

  give: {
    title: 'Ver',
    subtitle: 'Armağan kartlarını yönet.',
    tabMy: 'Armağanlarım',
    tabHistory: 'Verdiklerim',
    cardActive: 'Açık',
    cardInactive: 'Kapalı',
    newCard: 'Yeni Armağan',
    newCardTitle: 'Yeni Armağan',
    titleLabel: 'Başlık',
    descLabel: 'Açıklama',
    // Armağan türü
    giftTypeLabel: 'Tür',
    typeUnlimited: 'Sürekli açık',
    typeUnlimitedHint: 'Sınır yok — her zaman geçerli.',
    typeQuota: 'Kotası olan',
    typeQuotaHint: 'Belirli sayıda kullanım.',
    typeOnce: 'Tek seferlik',
    typeOnceHint: 'Bir kişi alır, kapanır.',
    quotaLabel: 'Kaç adet?',
    // Fiziksel/Dijital
    physicalLabel: 'Format',
    digital: 'Dijital',
    physical: 'Fiziksel',
    deliveryNoteLabel: 'Teslimat notu',
    deliveryNotePlaceholder: 'Kargo veya teslimat hakkında bilgi vermek ister misin? (isteğe bağlı)',
    deliveryNoteHint: 'Lojistik detaylar sohbet içinde karşılıklı halledilir, platform koordine etmez.',
    // Görünürlük
    visibilityLabel: 'Görünürlük',
    visTrustCircle: 'Güven Çemberi',
    visCommunity: 'Topluluk',
    visGlobal: 'Global',
    comingSoon: 'Yakında',
    // Diğer
    whyMeLabel: 'Neden sen?',
    whyMePlaceholder: 'Bunu neden sen veriyorsun, başkası değil?',
    optional: 'isteğe bağlı',
    create: 'Oluştur',
    cancel: 'Vazgeç',
    creating: 'Oluşturuluyor',
    empty: 'Henüz bir armağan yok.',
    historyEmpty: 'Henüz kimseye armağan vermedin.',
    error: 'Bir şey olmadı. Tekrar dener misin?',
    // Kart rozetleri
    badgeUnlimited: 'Sürekli',
    badgeOnce: 'Tek seferlik',
    badgeQuota: (n) => `${n} adet kaldı`,
    badgePhysical: 'Fiziksel',
    interested: (n) => n === 1 ? '1 talep' : `${n} talep`,
  },

  explore: {
    title: 'Keşfet',
    subtitle: 'Güven çemberinden ve ötesinden armağanlara göz at.',
    tabFeed: 'Armağanlar',
    tabHistory: 'Aldıklarım',
    filterTrustCircle: 'Güven Çemberi',
    filterCommunity: 'Topluluk',
    filterGlobal: 'Global',
    filterAll: 'Tümü',
    filterUnlimited: 'Sürekli',
    filterQuota: 'Kotası olan',
    filterOnce: 'Tek seferlik',
    filterPhysical: 'Fiziksel',
    requestSupport: 'İste',
    requesting: 'Gönderiliyor',
    empty: 'Henüz kimse burada değil.',
    historyEmpty: 'Henüz armağan almadın.',
    error: 'Bir şey olmadı. Tekrar dener misin?',
    markReceived: 'Teslim aldım',
    addToCircle: 'Güven çemberine ekle?',
    addToCircleHint: 'Bu kişiden armağan aldın. Güven çemberine eklemek ister misin?',
    addToCircleYes: 'Ekle',
    addToCircleSkip: 'Geç',
    added: 'Eklendi.',
    comingSoon: 'Yakında',
  },

  questions: {
    title: 'Sorular',
    subtitle: 'Cevaplarını görüntüle ve düzenle.',
    save: 'Kaydet',
    saving: 'Kaydediliyor',
    saved: 'Kaydedildi.',
    createCardLabel: 'Bu cevaptan armağan kartı oluştur.',
    error: 'Bir şey olmadı. Tekrar dener misin?',
  },

  trustTeam: {
    title: 'Güven Çemberi',
    subtitle: 'Güven çemberin ve davet ettiklerin.',
    tabCircle: 'Güven Çemberi',
    tabInvited: 'Davet Ettiklerim',
    invite: 'Davet Et',
    emptyCircle: 'Güven çemberin boş.',
    emptyCircleHint: 'Bir armağan aldıktan sonra "teslim aldım" diyerek o kişiyi buraya ekleyebilirsin.',
    emptyInvited: 'Henüz kimseyi davet etmedin.',
    subscriptionActive: 'Aktif',
    subscriptionEnded: 'Sona erdi',
    subscriptionPending: 'Beklemede',
    daysLeft: (n) => `${n} gün kaldı`,
    endSubscription: 'Sonlandır',
    gaveGift: 'sana armağan verdi',
    modal: {
      title: 'Birini davet et',
      step1: 'E-postası',
      step2: 'Süre',
      step3: 'Topluluk',
      step4: 'Kod',
      emailLabel: 'E-posta adresi',
      emailPlaceholder: 'isim@ornek.com',
      duration1: '1 ay',
      duration6: '6 ay',
      duration12: '12 ay',
      communityNew: 'Yeni topluluk',
      communityGeneral: 'Genel (topluluksuz)',
      communityExisting: 'Mevcut topluluk',
      communityNameLabel: 'Topluluk adı',
      membersAwareLabel: 'Üyeler bir isimli grubun parçası olduklarını bilsin',
      next: 'Devam',
      back: 'Geri',
      generate: 'Kod Oluştur',
      codeReady: 'Bu kodu paylaş',
      codeHint: 'Katılmak için bu koda ihtiyaçları var.',
      copy: 'Kopyala',
      copied: 'Kopyalandı!',
      close: 'Tamam',
    },
  },

  payment: {
    title: '1729\'a Katıl',
    subtitle: 'Devam etmek için davet kodu gerekli.',
    codeLabel: 'Davet kodu',
    codePlaceholder: 'XXXXXX',
    apply: 'Uygula',
    invalidCode: 'Geçersiz veya kullanılmış kod.',
    codeAccepted: 'Kod kabul edildi.',
    requireCode: 'Davet kodu gereklidir.',
    continue: 'Devam Et',
    processing: 'İşleniyor',
    testMode: 'Test modu — gerçek ödeme alınmıyor.',
    error: 'Bir şey olmadı. Tekrar dener misin?',
  },

  settings: {
    title: 'Ayarlar',
    subtitle: 'Hesap ve tercihlerini yönet.',

    // Görünüm
    appearance: 'Görünüm & Dil',
    theme: 'Tema',
    themeDark: 'Koyu',
    themeLight: 'Açık',
    themeSystem: 'Sistem',
    language: 'Dil',
    giftWord: 'Armağan kelimesi',
    giftWordDefault: 'Armağan',
    giftWordAlt: 'Şey',
    giftWordNote: 'Bu tercih sadece sana özel — başkaları her zaman kendi tercihlerinde görür.',

    // Abonelik
    subscription: 'Abonelik',
    plan: 'Plan',
    startDate: 'Başlangıç tarihi',
    endDate: 'Bitiş tarihi',
    daysLeft: (n) => `${n} gün kaldı`,
    type: 'Tür',
    typeGifted: 'Birinin hediyesi',
    typeSelf: 'Kendi aboneliği',
    managePayment: 'Ödemeyi yönet',
    comingSoon: 'Yakında',

    // Bildirimler
    notifications: 'E-posta bildirimleri',
    notifGiftInterest: 'Birileri armağanınla ilgilendi',
    notifGiftInterestHint: 'Armağanın etrafında bir sohbet başladığında.',
    notifNewMessage: 'Yeni mesaj',
    notifNewMessageHint: 'Aktif bir sohbette yeni mesaj aldığında.',
    notifSubExpiring: 'Abonelik bitiyor',
    notifSubExpiringHint: 'Erişimin bitmesine 5 gün kala.',
    notifSubExpired: 'Abonelik sona erdi',
    notifSubExpiredHint: 'Erişimin sona erdiğinde.',
    notifAddedToCircle: 'Birisinin çemberine eklendin',
    notifAddedToCircleHint: 'Biri seni güven çemberine eklediğinde.',
    notifQuotaEmpty: 'Armağan kotası doldu',
    notifQuotaEmptyHint: 'Kotası olan bir armağan tükendiğinde.',

    // Hesap
    account: 'Hesap',
    emailLabel: 'E-posta adresi',
    changePassword: 'Şifre değiştir',
    newPassword: 'Yeni şifre',
    updatePassword: 'Güncelle',
    passwordUpdated: 'Şifre güncellendi.',
    dangerZone: 'Tehlikeli bölge',
    deleteAccount: 'Hesabını ve tüm verilerini kalıcı olarak sil.',
    deleteConfirmPlaceholder: 'Silmek için SİL yaz',
    deleteConfirmWord: 'SİL',
    confirmDelete: 'Kalıcı olarak sil',

    saved: 'Kaydedildi.',
    error: 'Bir şey olmadı. Tekrar dener misin?',
  },

  language: { label: 'Dil', en: 'English', tr: 'Türkçe' },

  errors: {
    generic: 'Bir şey olmadı. Tekrar dener misin?',
    dbError: 'Bağlantı kurulamadı.',
  },
}

export default tr
